name: scgan-celeba
dataset: celeba
dataset_mode: celeba
dataroot: /data/datasets/CelebAMask-HQ
ngf: 48
ndf: 64
nrf: 32
nff: 32
netG: scg
position: true
pyr_pos: true
pyr_rng: 4
ig_sz: 7
ig_sigma: 1.5
ig_iter: 1
ig_relative: false
norm_G: spectralsccsyncbatch3x3
nThread: 16
num_experts_conv: 3
num_experts_norm: 3
weight_type: softmax
no_spectral_on_routing: true
rw_vgg: true
temperature: 0.05
dropblock: false
db_prob: 0.2
sampling: none
netD: multiscale
batchSize: 2
lambda_w_recon: 1.
smooth: false
use_vae: true
no_pairing_check: true
no_instance: true
niter: 50
save_epoch_freq: 5
niter_decay: 50
beta1: 0.
beta2: 0.999
