name: scgan-coco-best
dataset: coco
dataset_mode: coco
dataroot: /data/datasets/coco_stuff
ngf: 32
ndf: 64
nrf: 24
nff: 24
netG: scg
position: false
pyr_pos: false
pyr_rng: 5
ig_sz: 7
ig_sigma: 1.5
ig_iter: 1
ig_relative: false
norm_G: spectralsccsyncbatch3x3
nThread: 16
num_experts_conv: 2
num_experts_norm: 3
weight_type: softmax
no_spectral_on_routing: false
rw_vgg: true
temperature: 0.5
dropblock: false
db_prob: 0.2
sampling: none
netD: fpse
batchSize: 16
lambda_w_recon: 2.
smooth: false
use_vae: false
no_pairing_check: true
no_instance: true
niter: 100
save_epoch_freq: 10
niter_decay: 100
beta1: 0.
beta2: 0.999
